### ISSUE TITLE
Content before shortcode is rendered below shortcode - Karen

### ISSUE THREAD

**Issue by barkgj** [nexusthemes/wordpress-themes-portfolio#5]
On my theme portfolio page, I've added content before the portfolio shortcode; the content is displaying below the portfolio caetgory list. Does anyone else have this issue? (my site theme is not a Nexus theme)

**Comment by barkgj** [comment]
Asked for credentials to investigate.

**Comment by Kacem78** [comment]
This issue occurs also on the nexusthemes even hosted on the studio.

**Comment by barkgj** [comment]
Credentials are not needed; its possible to reproduce also in the environment of Kacem; if the shortcode is in the text widget, and you put a title on the text widget, the title of the text widget is rendered below too.

**Comment by barkgj** [comment]
I suggest to make this a task for the upworker too.

**Comment by barkgj** [comment]
Problem is resolved in the master version in GitHub.
